import type { Metadata } from "next";
import NavBar from '@/app/admin/components/NavBar';
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Safealert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavBar/>
      <body>
        <div className="contaier mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
